'-----------------------------------
' UML concepts illustrated
' JMB 2016
'-----------------------------------
@startuml
'-----------------------------------

class CLIENTS {
	NOM
	PRENOM
	SOLDE
}

'-----------------------------------
@enduml
'-----------------------------------